import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

/**
 * IMPORTANT: This Supabase client is ONLY used for token verification purposes.
 * It does NOT access Supabase database or storage.
 * All data operations are performed with SQLite database.
 * 
 * This client's sole purpose is to verify JWT tokens generated by Supabase Auth.
 */

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

// Use service role key if available, otherwise fall back to anon key
const supabaseKey = supabaseServiceKey || supabaseAnonKey;

if (!supabaseUrl || !supabaseKey) {
  throw new Error('Missing SUPABASE_URL and Supabase auth key');
}

// Log which key type we're using for debugging
if (supabaseServiceKey) {
  console.log('✅ Using Supabase service role key for token verification');
} else if (supabaseAnonKey) {
  console.log('⚠️  Using Supabase anon key for token verification (consider upgrading to service role key)');
} else {
  console.warn('❌ No valid Supabase key found! Authentication will not work.');
}

// Create minimal Supabase client only for auth token verification
const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});

// Export only the minimal client needed for auth verification
export default supabase;