-- Migration: 004_departments_courses_data.sql
-- Purpose: Add departments_courses table with course-to-class mappings
-- Date: 2026-04-02
-- 
-- This migration:
-- 1. Creates the departments_courses table to store department info with courses in JSON
-- 2. Populates it with pre-generated department/course/class seed data
-- 3. Adds a foreign key reference in the users table to link users.course to departments_courses

-- ===========================================================================
-- Create departments_courses table
-- ===========================================================================

create table if not exists public.departments_courses (
  id uuid primary key default gen_random_uuid(),
  department_name text unique not null,
  school text,
  
  -- JSON structure:
  -- {
  --   "Course Full Name": [
  --     {
  --       "class": "2BBA A",
  --       "term": 2,
  --       "room": "905",
  --       "block": "AUDI BLOCK"
  --     },
  --     ...
  --   ],
  --   ...
  -- }
  courses_json jsonb not null default '[]'::jsonb,
  
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Create index for department lookups
create index if not exists idx_departments_courses_name on public.departments_courses(lower(department_name));

-- ===========================================================================
-- Populate departments_courses with extracted Excel data
-- ===========================================================================

INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'BUSINESS AND MANAGEMENT  (BBA)', E'SCHOOL OF BUSINESS AND MANAGEMENT', '{"Bachelor of Business Administration (BBA) - Bangalore Central Campus": [{"class": "2BBA A", "term": 2}, {"class": "2BBA B", "term": 2}, {"class": "2BBA C", "term": 2}, {"class": "2BBA D", "term": 2}, {"class": "2BBA E", "term": 2}, {"class": "2BBA F", "term": 2}, {"class": "4BBAA", "term": 4}, {"class": "4BBAB", "term": 4}, {"class": "4BBAC", "term": 4}, {"class": "4BBAD", "term": 4}, {"class": "4BBAE", "term": 4}, {"class": "4BBAF", "term": 4}, {"class": "6BBAA", "term": 6}, {"class": "6BBAB", "term": 6}, {"class": "6BBAC", "term": 6}, {"class": "6BBAD", "term": 6}, {"class": "6BBAE", "term": 6}, {"class": "6BBAF", "term": 6}], "BBA (Decision Science) - Bangalore Central Campus": [{"class": "2BBADS", "term": 2}, {"class": "4BBADS", "term": 4}, {"class": "6BBADS", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'BUSINESS AND MANAGEMENT  (MBA)', E'SCHOOL OF BUSINESS AND MANAGEMENT', '{"MBA Bangalore Central Campus": [{"class": "2MBAG", "term": 2}, {"class": "2MBAH", "term": 2}, {"class": "2MBAI", "term": 2}, {"class": "2MBAJ", "term": 2}, {"class": "2MBAK", "term": 2}, {"class": "2MBAL", "term": 2}, {"class": "2MBAM", "term": 2}, {"class": "2MBAN", "term": 2}, {"class": "4MBA MAIN BA2", "term": 4}, {"class": "4MBA MAIN BA3", "term": 4}, {"class": "4MBA MAIN F4", "term": 4}, {"class": "4MBA MAIN F5", "term": 4}, {"class": "4MBA MAIN F6", "term": 4}, {"class": "4MBA MAIN F7", "term": 4}, {"class": "4MBA MAIN F8", "term": 4}, {"class": "4MBA MAIN HR", "term": 4}, {"class": "4MBA MAIN LOS3", "term": 4}, {"class": "4MBA MAIN LOS4", "term": 4}, {"class": "4MBA MAIN M4", "term": 4}, {"class": "4MBA MAIN M5", "term": 4}, {"class": "4MBA MAIN M6", "term": 4}, {"class": "4MBA MAIN M7", "term": 4}, {"class": "6MBA MAIN BA2", "term": 6}, {"class": "6MBA MAIN BA3", "term": 6}, {"class": "6MBA MAIN F4", "term": 6}, {"class": "6MBA MAIN F5", "term": 6}, {"class": "6MBA MAIN F6", "term": 6}, {"class": "6MBA MAIN F7", "term": 6}, {"class": "6MBA MAIN F8", "term": 6}, {"class": "6MBA MAIN HR", "term": 6}, {"class": "6MBA MAIN LOS3", "term": 6}, {"class": "6MBA MAIN LOS4", "term": 6}, {"class": "6MBA MAIN M4", "term": 6}, {"class": "6MBA MAIN M5", "term": 6}, {"class": "6MBA MAIN M6", "term": 6}, {"class": "6MBA MAIN M7", "term": 6}], "MBA with German MBA": [{"class": "2MBAT", "term": 2}, {"class": "4MBAT", "term": 4}], "MBA with MS Business (VCU, USA)": [{"class": "2MBAV", "term": 2}, {"class": "4MBAV", "term": 4}], "MBA (Christ University) with MBA (Western Michigan University USA)": [{"class": "2MBAW", "term": 2}, {"class": "4MBAW", "term": 4}], "MBA Executive": [{"class": "2MBAX", "term": 2}, {"class": "4MBAX", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'CHEMISTRY', E'SCHOOL OF SCIENCES', '{"BSc (Chemistry, Zoology) - Bangalore Central Campus": [{"class": "2BScCZ", "term": 2}, {"class": "4BScCZ", "term": 4}, {"class": "6BScCZ", "term": 6}], "MSc Chemistry": [{"class": "2MCHE", "term": 2}, {"class": "4MCHE", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'COMMERCE', E'SCHOOL OF COMMERCE FINANCE AND ACCOUNTANCY', '{"Bachelor of Commerce (BCom) - Bangalore Central Campus": [{"class": "2BCOM A", "term": 2}, {"class": "2BCOM B", "term": 2}, {"class": "2BCOM C", "term": 2}, {"class": "2BCOM D", "term": 2}, {"class": "4BCOMA", "term": 4}, {"class": "4BCOMB", "term": 4}, {"class": "4BCOMC", "term": 4}, {"class": "4BCOMD", "term": 4}, {"class": "6BCOMA", "term": 6}, {"class": "6BCOMB", "term": 6}, {"class": "6BCOMC", "term": 6}, {"class": "6BCOMD", "term": 6}], "BCom (Morning) - Bangalore Central Campus": [{"class": "2BCOM F", "term": 2}, {"class": "4BCOMF", "term": 4}, {"class": "6BCOMF", "term": 6}], "BCom (Accountancy and Taxation) - Bangalore Central Campus": [{"class": "2BCOMA&T", "term": 2}, {"class": "4BCOMA&T", "term": 4}, {"class": "6BCOMA&T", "term": 6}], "BCom (Applied Finance and Analytics) - Bangalore Central Campus": [{"class": "2BCOMAFA", "term": 2}, {"class": "4BCOMAFA", "term": 4}, {"class": "6BCOMAFA", "term": 6}], "BCom (Finance and Investment) - Bangalore Central Campus": [{"class": "2BCOMF&I A", "term": 2}, {"class": "2BCOMF&I B", "term": 2}, {"class": "4BCOMF&I A", "term": 4}, {"class": "4BCOMF&I B", "term": 4}, {"class": "6BCOMF&I A", "term": 6}, {"class": "6BCOMF&I B", "term": 6}], "BCom (Strategic Finance) - Bangalore Central Campus": [{"class": "2BCOMSF", "term": 2}, {"class": "4BCOMSF", "term": 4}, {"class": "6BCOMSF", "term": 6}], "BSc (Accountancy and Analytics) - Bangalore Central Campus": [{"class": "2BSc A&A", "term": 2}, {"class": "4BSc A&A", "term": 4}], "Master of Commerce": [{"class": "2MCOM", "term": 2}, {"class": "4MCOM", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'COMPUTER SCIENCE', E'SCHOOL OF SCIENCES', '{"Bachelor of Computer Applications (BCA) - Bangalore Central Campus": [{"class": "2BCA A", "term": 2}, {"class": "2BCA B", "term": 2}, {"class": "4BCA A", "term": 4}, {"class": "4BCA B", "term": 4}, {"class": "6BCA A", "term": 6}, {"class": "6BCA B", "term": 6}], "BSc (Computer Science, Mathematics) - Bangalore Central Campus": [{"class": "2BScCM", "term": 2}, {"class": "4BScCM", "term": 4}, {"class": "6BScCM", "term": 6}], "BSc (Computer Science, Statistics) - Bangalore Central Campus": [{"class": "2BScCS", "term": 2}, {"class": "4BScCS", "term": 4}, {"class": "6BScCS", "term": 6}], "Master of Computer Applications": [{"class": "2MCA A", "term": 2}, {"class": "2MCA B", "term": 2}, {"class": "4MCA A", "term": 4}, {"class": "4MCA B", "term": 4}, {"class": "6MCA A", "term": 6}, {"class": "6MCA B", "term": 6}], "Master of Science (Artificial Intelligence and Machine Learning)": [{"class": "2MSAIM", "term": 2}, {"class": "4MSAIM", "term": 4}, {"class": "6MSAIM", "term": 6}], "MSc (Computer Science and Applications)": [{"class": "2MSCSA", "term": 2}, {"class": "4MSCSA", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'ECONOMICS', E'SCHOOL OF SOCIAL SCIENCES', '{"MA Applied Economics": [{"class": "2MAECO", "term": 2}, {"class": "4MAECO", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'ENGLISH AND CULTURAL STUDIES', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"MA in English with Communication Studies": [{"class": "2MENG", "term": 2}, {"class": "4MENG", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'HOTEL MANAGEMENT', E'SCHOOL OF BUSINESS AND MANAGEMENT', '{"Bachelor of Hotel Management": [{"class": "2BHM", "term": 2}, {"class": "4BHM", "term": 4}, {"class": "6BHM", "term": 6}, {"class": "8BHM", "term": 8}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'INTERNATIONAL STUDIES, POLITICAL SCIENCE AND HISTORY', E'SCHOOL OF SOCIAL SCIENCES', '{"BA (History, Political Science) - Bangalore Central Campus": [{"class": "2BAHP", "term": 2}, {"class": "4BAHP", "term": 4}, {"class": "6BAHP", "term": 6}], "Master of Arts  in  International Studies": [{"class": "2MAIS", "term": 2}, {"class": "4MAIS", "term": 4}], "MA (Public Policy)": [{"class": "2MAPP", "term": 2}, {"class": "4MAPP", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'LIFE SCIENCES', E'SCHOOL OF SCIENCES', '{"BSc (Biotechnology, Botany) - Bangalore Central Campus": [{"class": "2BScBtB", "term": 2}, {"class": "4BScBtB", "term": 4}, {"class": "6BScBtB", "term": 6}], "BSc (Biotechnology, Chemistry) - Bangalore Central Campus": [{"class": "2BScBtC", "term": 2}, {"class": "4BScBtC", "term": 4}, {"class": "6BScBtC", "term": 6}], "BSc (Biotechnology, Forensic Science) - Bangalore Central Campus": [{"class": "2BScBtF", "term": 2}, {"class": "4BScBtF", "term": 4}, {"class": "6BScBtF", "term": 6}], "BSc (Biotechnology, Zoology) - Bangalore Central Campus": [{"class": "2BScBtZ", "term": 2}, {"class": "4BScBtZ", "term": 4}, {"class": "6BScBtZ", "term": 6}], "BSc (Life Sciences) - Bangalore Central Campus": [{"class": "2BScLIF", "term": 2}, {"class": "4BScLIF", "term": 4}, {"class": "6BScLIF", "term": 6}], "Master of Science in Botany": [{"class": "2MBOT", "term": 2}, {"class": "4MBOT", "term": 4}], "Master of Science in Biotechnology": [{"class": "2MBTY", "term": 2}, {"class": "4MBTY", "term": 4}], "MSc (Forensic Science)": [{"class": "2MFS", "term": 2}, {"class": "4MFS", "term": 4}], "Master of Science in Zoology": [{"class": "2MZOO", "term": 2}, {"class": "4MZOO", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'MATHEMATICS', E'SCHOOL OF SCIENCES', '{"BSc (Economics, Mathematics, Statistics) - Bangalore Central Campus": [{"class": "2EMS", "term": 2}, {"class": "4EMS", "term": 4}, {"class": "6EMS", "term": 6}], "MSc Mathematics": [{"class": "2MMAT", "term": 2}, {"class": "4MMAT", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'MEDIA STUDIES', E'SCHOOL OF SOCIAL SCIENCES', '{"BA (Communication and Media, English) - Bangalore Central Campus": [{"class": "2BACE", "term": 2}, {"class": "4BACE", "term": 4}, {"class": "6BACE", "term": 6}], "BA (Communication and Media, Psychology) - Bangalore Central Campus": [{"class": "2BACP", "term": 2}, {"class": "4BACP", "term": 4}, {"class": "6BACP", "term": 6}], "BA (Journalism and Digital Media, English) - Bangalore Central Campus": [{"class": "2BAJE", "term": 2}, {"class": "4BAJE", "term": 4}, {"class": "6BAJE", "term": 6}], "MA (Media and Communication Studies)": [{"class": "2MAMCS ACC", "term": 2}, {"class": "2MAMCS DTCS", "term": 2}, {"class": "4MAMCS ACC", "term": 4}, {"class": "4MAMCS MJ", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'MUSIC', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"BA (Music-Western Classical, Creative Media) - Bangalore Central Campus": [{"class": "2BAMC", "term": 2}, {"class": "4BAMC", "term": 4}, {"class": "6BAMC", "term": 6}], "BA (Music-Western Classical, Psychology) - Bangalore Central Campus": [{"class": "2BAMP", "term": 2}, {"class": "4BAMP", "term": 4}, {"class": "6BAMP", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PERFORMING ARTS', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"BA (Performing Arts, Creative Media) - Bangalore Central Campus": [{"class": "2BAPC", "term": 2}, {"class": "4BAPC", "term": 4}, {"class": "6BAPC", "term": 6}], "BA (Performing Arts, Psychology) - Bangalore Central Campus": [{"class": "2BAPP", "term": 2}, {"class": "4BAPP", "term": 4}, {"class": "6BAPP", "term": 6}], "MA (Performing Arts - Bharatanatyam)": [{"class": "2MPAB", "term": 2}, {"class": "4MPAB", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PHILOSOPHY AND THEOLOGY', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"Bachelor of Arts in Philosophy": [{"class": "2BPHL", "term": 2}, {"class": "4BPHL", "term": 4}, {"class": "6BPHL", "term": 6}], "MA Counselling and Spirituality": [{"class": "2MACS", "term": 2}, {"class": "4MACS", "term": 4}], "MA (Religion)": [{"class": "2MARL A", "term": 2}, {"class": "4MARL A", "term": 4}], "MA Philosophy": [{"class": "2MPHL", "term": 2}, {"class": "4MPHL", "term": 4}], "PG Diploma (Religion)": [{"class": "2PGDR A", "term": 2}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PHYSICS AND ELECTRONICS', E'SCHOOL OF SCIENCES', '{"BSc (Physics, Chemistry/Honours/Honours with Research) with minor in Mathematics": [{"class": "2BScPCm", "term": 2}], "BSc (Physics, Mathematics/Honours/Honours with Research) with minor in Astrophysics": [{"class": "2BScPMa", "term": 2}], "MSc Physics": [{"class": "2MPHY", "term": 2}, {"class": "4MPHY", "term": 4}], "BSc (Physics, Chemistry) - Bangalore Central Campus": [{"class": "4BScPC", "term": 4}, {"class": "6BScPC", "term": 6}], "BSc (Physics, Mathematics) - Bangalore Central Campus": [{"class": "4BScPM", "term": 4}, {"class": "6BScPM", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PROFESSIONAL STUDIES', E'SCHOOL OF COMMERCE FINANCE AND ACCOUNTANCY', '{"BCom (Branding and Entrepreneurship) - Bangalore Central Campus": [{"class": "2BCOM B&E", "term": 2}], "BCom (Finance and Accountancy) - Bangalore Central Campus": [{"class": "2BCOMF&A A", "term": 2}, {"class": "2BCOMF&A B", "term": 2}, {"class": "2BCOMF&A C", "term": 2}, {"class": "2BCOMF&A D", "term": 2}, {"class": "4BCOMF&A A", "term": 4}, {"class": "4BCOMF&A B", "term": 4}, {"class": "4BCOMF&A C", "term": 4}, {"class": "4BCOMF&A D", "term": 4}, {"class": "6BCOMF&A A", "term": 6}, {"class": "6BCOMF&A B", "term": 6}, {"class": "6BCOMF&A C", "term": 6}, {"class": "6BCOMF&A D", "term": 6}], "BCom (International Accountancy and Finance) - Bangalore Central Campus": [{"class": "2BCOMIAF A", "term": 2}, {"class": "2BCOMIAF B", "term": 2}, {"class": "2BCOMIAF C", "term": 2}, {"class": "4BCOMIAF A", "term": 4}, {"class": "4BCOMIAF B", "term": 4}, {"class": "4BCOMIAF C", "term": 4}, {"class": "6BCOMIAF A", "term": 6}, {"class": "6BCOMIAF B", "term": 6}], "BCom (International Finance) - Bangalore Central Campus": [{"class": "2BCOMIF A", "term": 2}, {"class": "2BCOMIF B", "term": 2}, {"class": "4BCOMIF A", "term": 4}, {"class": "4BCOMIF B", "term": 4}, {"class": "6BCOMIF", "term": 6}], "BCom (Professional) - Bangalore Central Campus": [{"class": "2BCOMP A", "term": 2}, {"class": "4BCOMP A", "term": 4}, {"class": "4BCOMP B", "term": 4}, {"class": "6BCOMP A", "term": 6}, {"class": "6BCOMP B", "term": 6}], "BSc (Actuarial Science) - Bangalore Central Campus": [{"class": "2BScAS", "term": 2}], "MCom (International Finance)": [{"class": "2MCOM IF", "term": 2}, {"class": "4MCOM IF", "term": 4}], "MSc Actuarial Science": [{"class": "2MSAS", "term": 2}, {"class": "4MSAS", "term": 4}], "MSc (Innovation and Entrepreneurship)": [{"class": "2MSIE", "term": 2}, {"class": "4MSIE", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PSYCHOLOGY', E'SCHOOL OF PSYCHOLOGICAL SCIENCES, EDUCATION AND SOCIAL WORK', '{"BA (Psychology, Economics) - Bangalore Central Campus": [{"class": "2BAPECO", "term": 2}, {"class": "4BAPECO", "term": 4}, {"class": "6BAPECO", "term": 6}], "BA (Psychology, English) - Bangalore Central Campus": [{"class": "2BAPENG", "term": 2}, {"class": "4BAPENG", "term": 4}, {"class": "6BAPENG", "term": 6}], "Master of Science in Psychology (Clinical)": [{"class": "2MPCL A", "term": 2}, {"class": "2MPCL B", "term": 2}, {"class": "4MPCL A", "term": 4}, {"class": "4MPCL B", "term": 4}], "Master of Science in Psychology (Counselling)": [{"class": "2MPCO", "term": 2}, {"class": "4MPCO", "term": 4}], "MSc (Clinical Psycho-Oncology)": [{"class": "2MPCPO", "term": 2}, {"class": "4MPCPO", "term": 4}], "Master of Science in Psychology (HRDM)": [{"class": "2MPHR", "term": 2}, {"class": "4MPHR", "term": 4}], "MSc (Psychology-HRDM) with MA (Business and Organisational Psychology) [Steinbeis, Germany]": [{"class": "2MPHRG", "term": 2}, {"class": "4MPHRG", "term": 4}], "MSc (Psychology- Health and Wellbeing)": [{"class": "2MPHW", "term": 2}, {"class": "4MPHW", "term": 4}], "Master of Science (Neuropsychology)": [{"class": "2MPNP", "term": 2}, {"class": "4MPNP", "term": 4}], "Master of Science (Educational Psychology)": [{"class": "2MSEDP", "term": 2}, {"class": "4MSEDP", "term": 4}], "PG Diploma in Counselling Psychology - Bangalore Central Campus": [{"class": "2PGDCP", "term": 2}], "BA Psychology (Honours) - Bangalore Central Campus": [{"class": "8BAPSY(H) BCC", "term": 8}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'SCHOOL OF EDUCATION', E'SCHOOL OF PSYCHOLOGICAL SCIENCES, EDUCATION AND SOCIAL WORK', '{"Bachelor of Education": [{"class": "2BEd A", "term": 2}, {"class": "2BEd B", "term": 2}, {"class": "4BEd A", "term": 4}, {"class": "4BEd B", "term": 4}], "Post Graduate Diploma in International Education(PGDIE)": [{"class": "2PGDIE", "term": 2}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'SCHOOL OF LAW', E'SCHOOL OF LAW', '{"BA LLB (Honours)": [{"class": "10BALLB A", "term": 10}, {"class": "10BALLB B", "term": 10}, {"class": "10BALLB C", "term": 10}, {"class": "2BALLB A", "term": 2}, {"class": "2BALLB B", "term": 2}, {"class": "2BALLB C", "term": 2}, {"class": "4BALLB A", "term": 4}, {"class": "4BALLB B", "term": 4}, {"class": "4BALLB C", "term": 4}, {"class": "6BALLB A", "term": 6}, {"class": "6BALLB B", "term": 6}, {"class": "6BALLB C", "term": 6}, {"class": "8BALLB A", "term": 8}, {"class": "8BALLB B", "term": 8}, {"class": "8BALLB C", "term": 8}], "BBA LLB (Honours)": [{"class": "10BBALLB A", "term": 10}, {"class": "10BBALLB B", "term": 10}, {"class": "2BBALLB A", "term": 2}, {"class": "2BBALLB B", "term": 2}, {"class": "2BBALLB C", "term": 2}, {"class": "4BBALLB A", "term": 4}, {"class": "4BBALLB B", "term": 4}, {"class": "6BBALLB A", "term": 6}, {"class": "6BBALLB B", "term": 6}, {"class": "8BBALLB A", "term": 8}, {"class": "8BBALLB B", "term": 8}], "Master of Law (LLM) in Constitutional and Administrative Law": [{"class": "2LLMCAL", "term": 2}], "Master of Law (LLM) in Corporate and Commercial Law": [{"class": "2LLMCCL", "term": 2}], "Master of Law (LLM) in Intellectual Property and Trade Law": [{"class": "2LLMIPL", "term": 2}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'SOCIAL WORK', E'SCHOOL OF PSYCHOLOGICAL SCIENCES, EDUCATION AND SOCIAL WORK', '{"MSW Clinical and Community Practice": [{"class": "2MSWCC", "term": 2}, {"class": "4MSWCC", "term": 4}], "MSW Human Resources Development and Management": [{"class": "2MSWHR", "term": 2}, {"class": "4MSWHR", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'SOCIOLOGY', E'SCHOOL OF SOCIAL SCIENCES', '{"BA (Economics, Sociology) - Bangalore Central Campus": [{"class": "2BAES", "term": 2}, {"class": "4BAES", "term": 4}, {"class": "6BAES", "term": 6}], "MA Applied Sociology": [{"class": "2MSOC", "term": 2}, {"class": "4MSOC", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'STATISTICS AND DATA SCIENCE', E'SCHOOL OF SCIENCES', '{"BSc (Data Science, Mathematics) - Bangalore Central Campus": [{"class": "2BScDM", "term": 2}, {"class": "4BScDM", "term": 4}, {"class": "6BScDM", "term": 6}], "BSc (Data Science, Statistics) - Bangalore Central Campus": [{"class": "2BScDS", "term": 2}, {"class": "4BScDS", "term": 4}, {"class": "6BScDS", "term": 6}], "Master of Science (Data Science)": [{"class": "2MDS", "term": 2}, {"class": "4MDS", "term": 4}, {"class": "6MDS", "term": 6}], "MSc (Computational Statistics and Applied AI)": [{"class": "2MSCSA AI", "term": 2}, {"class": "4MSCSA AI", "term": 4}], "MSc Data Analytics and Artificial Intelligence and MA Data Analytics and Artificial Intelligence (Steinbeis University, Germany) - Bangalore Central Campus": [{"class": "2MSD A&A", "term": 2}], "MSc (Statistics)": [{"class": "2MSTAT", "term": 2}, {"class": "4MSTAT", "term": 4}, {"class": "6MSTAT", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'THEATRE STUDIES', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"BA (Theatre Studies, Creative Media) - Bangalore Central Campus": [{"class": "2BATC", "term": 2}, {"class": "4BATC", "term": 4}, {"class": "6BATC", "term": 6}], "BA (Theatre Studies, Psychology) - Bangalore Central Campus": [{"class": "2BATP", "term": 2}, {"class": "4BATP", "term": 4}, {"class": "6BATP", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;

-- ===========================================================================
-- Auto-updated timestamps for departments_courses
-- ===========================================================================

drop trigger if exists trg_departments_courses_updated_at on public.departments_courses;
create trigger trg_departments_courses_updated_at
before update on public.departments_courses
for each row execute function public.set_updated_at();

